name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Scheduled daily
  workflow_dispatch:   # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Save current commit hash
        id: premerge
        run: echo "PRE_MERGE_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Add upstream remote
        run: git remote add upstream https://github.com/martindstone/WebGoat.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes into main
        run: |
          git checkout main
          git merge upstream/main -X ours --no-edit

      - name: Send commit notifications
        env:
          CORTEX_API_TOKEN: ${{ secrets.CORTEX_API_TOKEN }}
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          PRE_COMMIT=$PRE_MERGE_HASH
          NEW_COMMIT=$(git rev-parse HEAD)
          echo "Pre-merge commit: $PRE_COMMIT"
          echo "New commit: $NEW_COMMIT"
          # List all commits between the old and new commit
          COMMITS=$(git log --no-merges --format="%H" ${PRE_COMMIT}..${NEW_COMMIT})
          echo "New commits:"
          echo "$COMMITS"
          for COMMIT in $COMMITS; do
            echo "Processing commit: $COMMIT"
            # Extract the ISO8601 timestamp
            TIMESTAMP=$(git show -s --format=%cI $COMMIT)
            # Get the full commit message (flatten newlines)
            MESSAGE=$(git show -s --format=%B $COMMIT | tr '\n' ' ' | xargs)
            # Get the short commit hash
            SHORT_HASH=$(git rev-parse --short $COMMIT)
            # Construct the commit URL
            COMMIT_URL="$REPO_URL/commit/$COMMIT"
            echo "Sending notification for commit: $COMMIT"
            curl -X POST -H "Content-Type: application/json" \
              -H "Authorization: Bearer $CORTEX_API_TOKEN" \
              -d "{\"commit\": \"${COMMIT}\", \"short_hash\": \"${SHORT_HASH}\", \"timestamp\": \"${TIMESTAMP}\", \"message\": \"${MESSAGE}\", \"url\": \"${COMMIT_URL}\"}" \
              https://webhook.site/e77128be-28c5-43e1-94eb-238e98e5dfad
          done

      - name: Push changes to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
